version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: queries_challenge
    ports:
      - 5432:5432  